import json
import time
import os
import re
import subprocess
import sys
from pathlib import Path

from playwright.sync_api import sync_playwright, Page
import openai
import time

openai.api_key="Insert api key here"
PROMPT_TEMPLATE = '''You are an expert QA automation engineer.
Given the HTML of a webpage and a natural language test case description, generate a single Playwright Python test function using the sync API that performs the described task.

✅ Required Constraints:
For commands like "Open https://...", the function must use page.goto("<url>") and nothing else
Use the sync API from playwright.sync_api.
The function name must be f{idx} (e.g., f1, f2, ...).
The function must take a single argument: page: Page.
Only generate one function per request.
Only use page.goto() when the command explicitly asks to open a URL.
Do not include:
  - Browser or context setup (e.g., with sync_playwright(), browser =, page.goto()).
  - if __name__ == "__main__": blocks.
  - No extra functions should be included.
  - Do NOT include run_all_tests function.
Please generate the Python function definitions without including -> None in the function signature.
Use "time.sleep(1)" after each major action (e.g., click, fill).
Do not use expect() or any async methods.
Use query_selector() or query_selector_all() where appropriate.
Use visible label-based selection only if no IDs/classes are found in the HTML.
Do NOT include any prerequisite steps. Only implement the specific task described in the command.
For text verification, use "in" comparisons instead of exact matches (e.g., "expected_text in actual_text") unless the test explicitly requires exact matching.
Ensure no syntax errors, no unclosed strings, proper indentation, and no mixing of sync/async APIs.
Avoid reusing variable names unnecessarily.
Avoid duplicate or redundant actions.
Keep the code clean and modular."
"
---

📥 Input:
HTML: {html}
Test case: {command}

---

Now, generate the function named f{idx} accordingly. ONLY OUTPUT THE FUNCTION CODE, nothing else.'''





def call_openai_for_test_function(html, command, idx, node_type):
    """
    Generates a Playwright test function using the OpenAI API based on HTML content and a user command.

    Args:
        html (str): The HTML source code of the current page.
        command (str): A natural-language instruction describing the desired test action.
        idx (int): The index of the test function being generated (used for naming or ordering).
        node_type (str): The type of node in the test plan (e.g., "action" or "test"). If "test",
                         the model will be instructed to only verify page content, without interaction.

    Returns:
        str: The code content of the generated test function.
    """

    prompt = PROMPT_TEMPLATE
    if node_type == "test":
        prompt += "\n\nOnly perform content verification (e.g., using inner_text assertions). Do NOT click, fill, or interact with the page in any way."
    prompt = prompt.format(html=html, command=command, idx=idx)

    # Get the response from OpenAI
    response = openai.ChatCompletion.create(
        model="gpt-4.1-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        max_tokens=1800
    )

    # Extract the content we need to return
    content = response.choices[0].message['content']

    # Prepare the response in the desired format for printing
    result = {
        "id": response.id,
        "object": response.object,
        "created": int(time.time()),  # This will be the current timestamp
        "model": response.model,
        "usage": {
            "prompt_tokens": response.usage['prompt_tokens'],
            "completion_tokens": response.usage['completion_tokens'],
            "total_tokens": response.usage['total_tokens']
        },
        "choices": [
            {
                "message": {
                    "role": response.choices[0].message['role'],
                    "content": content
                }
            }
        ]
    }

    # Print the response in JSON-like format
    print(result)
    print(content)
    # Return just the content for function processing
    return content

def clean_generated_code(code: str,idx:int) -> str:
    """
    Cleans and extracts a single Playwright test function from the response
    returned by OpenAI. Ensures the output is a properly formatted,
    standalone Python function suitable for direct execution.

    Args:
        code (str): The raw code string generated by the LLM (may include markdown, multiple functions, etc.).
        idx (int): The index of the test function (currently unused, but may be useful for future enhancements).

    Returns:
        str: A clean Playwright test function starting with `def fX(page: Page): ...`.
    """
    # Remove code blocks
    code = re.sub(r"python\s*", "", code)
    code = re.sub(r"", "", code)
    code = re.sub(r"```", "", code)
    # Extract only the function definition
    #function_match = re.search(r"def f\d+\(page: Page\):.*?(?=def|\Z)", code, re.DOTALL)
    function_match = re.search(r"def f\d+\(page(?:: Page)?\):.*?(?=^def|\Z)", code, re.DOTALL | re.MULTILINE)

    if function_match:
        code = function_match.group(0).strip()
    else:
        # If the regex didn't match, try a more basic approach
        lines = code.splitlines()
        function_lines = []
        inside_function = False
        
        for line in lines:
            if (line.strip().startswith("def f") and "page: Page" in line) or (line.strip().startswith("def f") and "page" in line):
                inside_function = True
                function_lines.append(line)
            elif inside_function:
                if line.strip().startswith("def ") or line.strip().startswith("with sync_playwright"):
                    inside_function = False
                else:
                    function_lines.append(line)
        
        code = "\n".join(function_lines).strip()
    return code

def extract_html_from_url(page, url: str):
    """
    Navigates the Playwright page to the given URL and returns the HTML content of the loaded page.

    Args:
        page: The Playwright page object used to navigate and interact with the browser.
        url (str): The URL of the webpage to fetch the HTML content from.

    Returns:
        str: The full HTML content of the page after navigation.
             Returns an empty string if no URL is provided. 
    """
    if not url:
        print("⚠️ No URL available to fetch HTML.")
        return ""
    page.goto(url)
    time.sleep(3)
    return page.content()

def get_existing_function_count():
    """
    Counts how many test functions following the naming pattern `fX` (e.g., f1, f2, ...) 
    currently exist in the file `sample_tester.py`.

    Returns:
        int: The number of existing test functions found in the file.
             Returns 0 if the file does not exist. 
    """
    if not Path(sys.argv[2]).exists():
        return 0
    with open(sys.argv[2]) as f:
        return len(re.findall(r"^def f\d+\(", f.read(), re.M))

def ensure_script_header():
    """Ensures that the test script file `sample_tester.py` exists.
    If the file does not exist, it creates the file and writes a standard header with essential imports,
    including Playwright sync API, time, sys, pathlib, and a custom module `my_custom`.

    This helps prepare the test script file for appending generated test functions later on.
    """
    file_path = sys.argv[2]
    if not Path(file_path).exists():
        with open(file_path, "w") as f:
            f.write("from playwright.sync_api import sync_playwright, Page\nimport time\nimport sys\nfrom pathlib import Path\nimport my_custom\n")

def append_function_to_test_script(new_func: str):
    """
    Appends a new test function to the test script file `sample_tester.py`.

    Before appending, it removes any existing `run_all_tests` function and the
    `__main__` block that calls it, to allow regeneration of those sections later
    with updated content.

    Args:
        new_func (str): The string containing the new test function code to append.

    Behavior:
        - If the file exists, it loads the current content, strips out any existing
          `run_all_tests` and `__main__` block to avoid duplicates.
        - Then, it appends the new function code at the end of the file with spacing.
    """
    # Check if the file exists and read its content
    file_path = sys.argv[2]
    if Path(file_path).exists():
        with open(file_path, "r") as f:
            content = f.read()
        
        # Remove any existing run_all_tests function and __main__ block
        content = re.sub(r"def run_all_tests.*?if __name__ == ['\"]__main__['\"]:.*?run_all_tests\(.*?\)\n?", "", content, flags=re.DOTALL)

        
        # Write the content back without run_all_tests and __main__ block
        if content.strip():
            with open(file_path, "w") as f:
                f.write(content.strip() + "\n\n")
    
    # Append the new function
    with open(file_path, "a") as f:
        f.write(new_func + "\n\n")

def regenerate_run_all_tests(upto: int, plan=None):
    """
    Regenerate the run_all_tests function based on the original test plan order.
    
    Args:
        upto: The maximum number of tests to run
        plan: The original test plan from the JSON file
    """
    import re
    from pathlib import Path
    
    # Read the existing test file
    with open(sys.argv[2], "r") as f:
        content = f.read()
    
    # Check if my_custom.py exists before trying to read it
    custom_content = ""
    if Path("my_custom.py").exists():
        with open("my_custom.py", "r") as c:
            custom_content = c.read()
    
    # Extract all defined fN and my_custom_testN functions to verify they exist
    f_matches = {name: True for name in re.findall(r"def (f\d+)\(page(?:: Page)?\):", content)}
    custom_matches = {name: True for name in re.findall(r"def (my_custom_test\d+)\(page(?:: Page)?\):", custom_content)} if custom_content else {}
    
    # Start constructing the new run_all_tests block
    run_all_tests = "def run_all_tests(upto=999):\n"
    run_all_tests += "    with sync_playwright() as p:\n"
    run_all_tests += "        browser = p.chromium.launch(headless=False, slow_mo=500)\n"
    run_all_tests += "        context = browser.new_context()\n"
    run_all_tests += "        page = context.new_page()\n"

    # Build the test_functions dictionary based on the original plan order
    run_all_tests += "        test_functions = {\n"
    
    if plan:
        # Use the original plan order to maintain sequence
        custom_count = 0
        for i, node in enumerate(plan["nodes"], start=1):
            if node["type"] == "custom":
                custom_count += 1
                custom_func_name = f"my_custom_test{custom_count}"
                if custom_func_name in custom_matches:
                    run_all_tests += f"            {i}: my_custom.{custom_func_name},\n"
            else:
                func_name = f"f{i}"
                if func_name in f_matches:
                    run_all_tests += f"            {i}: {func_name},\n"
    else:
        # Fallback to alphabetical sorting if plan isn't provided
        f_funcs = sorted([name for name in f_matches.keys()], key=lambda x: int(x[1:]))
        custom_funcs = sorted([name for name in custom_matches.keys()], key=lambda x: int(x[12:]))
        
        for i, func in enumerate(f_funcs + [f"my_custom.{name}" for name in custom_funcs], start=1):
            run_all_tests += f"            {i}: {func},\n"
            
    run_all_tests += "        }\n\n"

    # Loop through and run each test function
    run_all_tests += "        import re\n"
    run_all_tests += "        for i in range(1, upto + 1):\n"
    run_all_tests += "            if i in test_functions:\n"
    run_all_tests += "                print(\"running test_functions\", i)\n"
    run_all_tests += "                test_functions[i](page)\n\n"
    run_all_tests += "                html = page.content()\n"
    run_all_tests += "                html = re.sub(r'<style.*?>.*?</style>', '', html, flags=re.DOTALL | re.IGNORECASE)\n"
    run_all_tests += "                html = re.sub(r'<script.*?>.*?</script>', '', html, flags=re.DOTALL | re.IGNORECASE)\n"
    run_all_tests += "                with open(\"current_html.html\", \"w\", encoding=\"utf-8\") as f:\n"
    run_all_tests += "                    f.write(html)\n\n"

    run_all_tests += "        print(\"Success\")\n"
    run_all_tests += "        browser.close()\n\n"

    # Append __main__ block
    run_all_tests += "if __name__ == '__main__':\n"
    run_all_tests += "    import sys\n"
    run_all_tests += "    from playwright.sync_api import sync_playwright, Page\n"
    run_all_tests += "    import my_custom\n"
    run_all_tests += "    upto = int(sys.argv[1]) if len(sys.argv) > 1 else 999\n"
    run_all_tests += "    run_all_tests(upto)\n"

    # Remove old run_all_tests and main block
    content = re.sub(r"if __name__ == ['\"]__main__['\"]:.*?run_all_tests\(upto\)", "", content, flags=re.DOTALL)
    content = re.sub(r"def run_all_tests\(.*?\n(?:    .*\n)*?browser\.close\(\)\n\n", "", content, flags=re.DOTALL)

    # Append regenerated logic
    content = content.strip() + "\n\n" + run_all_tests

    # Rewrite the test file
    with open(sys.argv[2], "w") as f:
        f.write(content)

def remove_style_script(html):
    """
    Removes all <style> and <script> blocks from the given HTML string.
    Args:
        html (str): The HTML content as a string.

    Returns:
        str: The cleaned HTML string with all <style> and <script> blocks removed.
    """
    # Remove <style>...</style> blocks (case-insensitive, dot matches newline)
    html = re.sub(r'<style.*?>.*?</style>', '', html, flags=re.DOTALL | re.IGNORECASE)
    
    # Remove <script>...</script> blocks (case-insensitive, dot matches newline)
    html = re.sub(r'<script.*?>.*?</script>', '', html, flags=re.DOTALL | re.IGNORECASE)
    
    return html

def generate_function_from_test_node(node, idx, prior_nodes):
    """
    Creates a Playwright test function from a single test step and prior context.

    Finds the last opened URL from previous steps.
    Loads saved HTML from current_html.html if available.
    Otherwise, opens the URL in a browser and extracts HTML using extract_html_from_url.
    Cleans HTML with remove_style_script.
    Sends HTML and command to OpenAI via call_openai_for_test_function to generate test code.   
    Cleans and extracts the function code using clean_generated_code.

    Args:
        node (dict): The current test step info (like what action to do).
        idx (int): The number/index of this test step — used to name the function.
        prior_nodes (list): Earlier test steps, so it can figure out context like the last opened URL.

    Returns:
        str: The cleaned-up Python function code that performs the test step.
    """
    command = node["command"]
    url = None
    for past_node in reversed(prior_nodes):
        if past_node["type"] == "action" and past_node["command"].startswith("Open "):
            url = past_node["command"].split("Open ")[1]
            break

    html = ""
    if not command.startswith("Open "):
        # First check if we have a saved HTML file from previous function
        if Path("current_html.html").exists():
            try:
                with open("current_html.html", "r", encoding="utf-8") as f:
                    html = f.read()
                    html= remove_style_script(html)
                print("📄 Using HTML from saved file")
            except Exception as e:
                print(f"⚠️ Error reading HTML file: {e}")
                
        # Fall back to browser extraction if no file or empty file
        if not html and url:
            print("🌐 Extracting HTML from browser")
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=False, slow_mo=500)
                context = browser.new_context()
                page = context.new_page()
                html = extract_html_from_url(page, url)
                html= remove_style_script(html)
                with open("current_html.html", "w", encoding="utf-8") as f:
                    f.write(html)
                browser.close()

    generated_code = call_openai_for_test_function(html, command, idx, node["type"])
    return clean_generated_code(generated_code,idx)

def main():
    """
    Runs the whole test process step-by-step.

    - Deletes old test script and saved HTML so we start fresh.
    - Loads the list of tests from 'sample_tests.json'.
    - Adds necessary imports to the test script.
    - Goes through each test in the list:
      - Skips tests that are already done.
      - For custom tests, updates the runner to include them.
      - For normal tests, generates new test code and adds it to the script.
    - Runs the test script up to the current test, with a timeout to avoid freezes.
    """
    # Delete existing sample_tester.py to start fresh
    if Path(sys.argv[2]).exists():
        try:
            Path(sys.argv[2]).unlink()
            print(f"Removed existing {sys.argv[2]} to start fresh")
        except Exception as e:
            print(f"Warning: Could not remove existing {sys.argv[2]}: {e}")
    
    # Also remove any existing HTML file
    if Path("current_html.html").exists():
        try:
            Path("current_html.html").unlink()
            print("Removed existing current_html.html to start fresh")
        except Exception as e:
            print(f"Warning: Could not remove existing current_html.html: {e}")

    # Load the test plan
    with open(sys.argv[1]) as f:
        plan = json.load(f)
    # Initialize my_custom.py if it doesn't exist and custom_tests_file is specified
    if "custom_tests_file" in plan and not Path(plan["custom_tests_file"]).exists():
        with open(plan["custom_tests_file"], "w") as f:
            f.write("from playwright.sync_api import Page\nimport time\n\n")
            print(f"Created empty {plan['custom_tests_file']} file")

    ensure_script_header()
    total_nodes = len(plan["nodes"])
    custom_test_count = 0
    
    for i, node in enumerate(plan["nodes"]):
        idx = i + 1
        if idx <= get_existing_function_count():
            continue
            
        # Handle different node types
        if node["type"] == "custom":
            # For custom nodes, we don't generate code, just make sure the entry in run_all_tests points to my_custom.py
            print(f"📌 Processing custom node {idx}: {node['command']}")
            custom_test_count += 1
            # Just regenerate run_all_tests to include the custom test references
            regenerate_run_all_tests(idx, plan)
        elif node["type"] in ("action", "test"):
            # For regular action or test nodes, generate code as before
            print(f"⚙️ Generating f{idx} for: {node['command']}")
            new_func = generate_function_from_test_node(node, idx, plan["nodes"][:idx])
            append_function_to_test_script(new_func)
            regenerate_run_all_tests(idx, plan)
        else:
            print(f"⏭️ Skipping unsupported node type: {node['type']}")
            continue
        
        try:
            # Run the test with a timeout to avoid hanging
            subprocess.run(["python", sys.argv[2], str(idx)], timeout=300)
            #subprocess.run(["python", "sample_tester.py", str(idx)], timeout=3000)
        except subprocess.TimeoutExpired:
            print(f"⚠️ Test execution timed out for step {idx}")

if __name__ == "__main__":
    main()
